# Generated by Django 2.2.12 on 2020-05-03 17:34

from django.db import migrations, models
import macaddress.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Created date and time')),
                ('name', models.CharField(help_text='Device name to identify', max_length=100)),
                ('mac_address', macaddress.fields.MACAddressField(help_text='Unique Device MAC address', integer=True, unique=True)),
                ('hardware', models.CharField(choices=[('RP', 'Raspberry Pi 4 Model B')], default='RP', max_length=10)),
                ('location', models.CharField(help_text='Device Location', max_length=100)),
                ('last_checkin_dt', models.DateTimeField(verbose_name='Last Check-in from device to platform')),
            ],
        ),
    ]
