# Generated by Django 2.2.12 on 2020-05-03 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_added_by_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='last_checkin_dt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last Check-in from device to platform'),
        ),
    ]
