# Generated by Django 2.2.12 on 2020-05-22 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20200503_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='location',
            field=models.CharField(help_text='Device Location for weather data, etc', max_length=100),
        ),
    ]
