# Generated by Django 2.2.12 on 2020-05-03 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Control',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_dt', models.DateTimeField(auto_now_add=True, verbose_name='Created date and time')),
                ('pin_number', models.PositiveIntegerField(verbose_name='Device Pin number')),
                ('name', models.CharField(help_text='Control name to identify. For example: "Pump 2"', max_length=100)),
                ('type', models.CharField(choices=[('PU', 'Pump'), ('BU', 'Button')], default='PU', max_length=10)),
                ('state', models.BooleanField(default=False, help_text='This is the current state (on/off) of the pump.')),
                ('last_changed', models.DateTimeField(help_text='The last time that the "state" value was updated.')),
                ('user_last_changed', models.DateTimeField(help_text='The last time that the "state" value was updated by user.')),
            ],
        ),
    ]
