# Generated by Django 2.2.12 on 2020-05-03 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('controls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='control',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='devices.Device'),
        ),
    ]
