# Generated by Django 2.2.12 on 2020-05-03 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controls', '0002_control_device'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='last_changed',
            field=models.DateTimeField(blank=True, help_text='The last time that the "state" value was updated.', null=True),
        ),
        migrations.AlterField(
            model_name='control',
            name='pin_number',
            field=models.PositiveIntegerField(help_text='This is the Device GPIO pin number that will be used'),
        ),
        migrations.AlterField(
            model_name='control',
            name='state',
            field=models.BooleanField(default=False, help_text='This is the current state (on/off) of this control.'),
        ),
        migrations.AlterField(
            model_name='control',
            name='type',
            field=models.CharField(choices=[('PU', 'Pump'), ('BU', 'Button')], default='PU', help_text='The type of object over which the GPIO pin will have control.', max_length=10),
        ),
    ]
