# Generated by Django 2.2.12 on 2020-05-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_auto_20200503_1817'),
        ('controls', '0003_auto_20200503_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='control',
            name='user_last_changed',
            field=models.DateTimeField(blank=True, help_text='The last time that the "state" value was updated by user.', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='control',
            unique_together={('device', 'pin_number')},
        ),
    ]
